### ISSUE TITLE
Access the target name from config.rb

### ISSUE THREAD

**Issue by pomartel** [middlemac/middleman-targets#1]
Is there a way to access the `target_name` or any other helper method in the `config.rb` file?

Thanks!

**Comment by balthisar** [comment]
Sorry I didn't see this earlier. Right now Middleman itself doesn't provide a means to do this, as their intention is to sandbox the `config.rb` from the rest of the application.

What are you trying to accomplish? Maybe I can help suggest a workaround.

**Comment by pomartel** [comment]
Thanks for your help!

I thought maybe this API could be used to expose the target to the configuration: https://middlemanapp.com/advanced/custom_extensions/#adding-methods-to-config-rb

In the config, I specify different deployment variables for S3 and Cloudfront. The deployed domains vary in function of the target.

**Comment by balthisar** [comment]
Ah, yes, I see. I will make a note of that and add it soon.

**Comment by balthisar** [comment]
Oh, my, better late than never, but I pushed 1.0.8, which offers `middleman_target` exposed to the `config.rb` file.
